# Generated by Django 5.2 on 2025-08-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'فرم تماس با ما', 'verbose_name_plural': 'فرم های تماس با ما'},
        ),
    ]
