# Generated by Django 4.2 on 2025-08-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(db_index=True, max_length=512, verbose_name='توضیحات کوتاه'),
        ),
    ]
