# Generated by Django 5.2 on 2026-01-10 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='title_in_url',
            field=models.CharField(blank=True, db_index=True, max_length=300, null=True, verbose_name='نام برند در URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productbrand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(max_length=300, verbose_name='نام برند'),
        ),
    ]
