# Generated by Django 4.2 on 2025-07-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=512, null=True, verbose_name='توضیحات کوتاه'),
        ),
    ]
