# Generated by Django 4.2 on 2025-07-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_category_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title_in_url',
            field=models.CharField(max_length=300, null=True, verbose_name='عنوان در url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=300, verbose_name='عنوان'),
        ),
    ]
