# Generated by Django 5.2 on 2025-08-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=300, verbose_name='نام سایت')),
                ('site_domain', models.CharField(max_length=300, verbose_name='دامنه سایت')),
                ('site_logo', models.ImageField(upload_to='images/site_settings', verbose_name='لوگو سایت')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('address', models.CharField(max_length=400, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='تلفن')),
                ('fax', models.CharField(max_length=20, verbose_name='فکس')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('copyright_text', models.CharField(max_length=300, verbose_name='متن کپی رایت')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
