# Generated by Django 5.2 on 2025-09-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلایدرها'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='desription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/sliders', verbose_name='تصویر اسلایدر'),
        ),
    ]
