# Generated by Django 5.2 on 2026-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_slider_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='عنوان')),
                ('url', models.URLField(blank=True, max_length=512, null=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('is_deleted', models.BooleanField(verbose_name='حذف شده / نشده')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
