# Generated by Django 5.2 on 2026-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_commercialbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbanner',
            name='position',
            field=models.CharField(blank=True, choices=[('main_page', 'صفحه اصلی'), ('product_detail_page', 'صفحه جزئیات محصول'), ('products_list_page', 'صفحه لیست محصولات'), ('blog_detail_page', 'صفحه جزئیات مقاله'), ('blogs_list_page', 'صفحه لیست مقالات')], max_length=125, null=True, verbose_name='صفحه نمایش بنر'),
        ),
    ]
