# Generated by Django 5.2 on 2026-02-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_alter_commercialbanner_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbanner',
            name='position',
            field=models.CharField(choices=[('product_detail_page', 'صفحه جزئیات محصول'), ('products_list_page', 'صفحه لیست محصولات'), ('blog_detail_page', 'صفحه جزئیات مقاله'), ('blogs_list_page', 'صفحه لیست مقالات')], default='main_page', max_length=125, verbose_name='صفحه نمایش بنر'),
        ),
    ]
