# Generated by Django 5.2 on 2025-09-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.CharField(max_length=300, verbose_name='عنوان در URL'),
        ),
    ]
