# Generated by Django 5.2 on 2025-09-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlecategory_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='images/articles')),
                ('short_description', models.TextField(verbose_name='توضیحات کوتاه')),
                ('text', models.TextField(verbose_name='متن کامل مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('categories', models.ManyToManyField(related_name='articles', to='article.articlecategory', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
