# Generated by Django 5.2 on 2025-09-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله'),
        ),
    ]
