# Generated by Django 5.2 on 2025-09-30 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_created_date_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 19, 2, 2, 686453), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
