# Generated by Django 5.2 on 2025-10-22 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_article_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 22, 18, 35, 31, 357707), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
