# Generated by Django 5.2 on 2025-11-08 07:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_article_created_date_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 8, 11, 24, 30, 283494), editable=False, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='article.articlecomment', verbose_name='والد'),
        ),
    ]
