# Generated by Django 5.2 on 2025-11-20 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_article_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 16, 42, 25, 90988), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
