# Generated by Django 5.2 on 2026-01-10 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_article_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 10, 13, 17, 34, 561747), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
