# Generated by Django 5.2 on 2026-02-13 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_article_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 17, 40, 24, 98780), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
