# Generated by Django 5.2 on 2026-02-14 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_alter_article_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 11, 20, 51, 858859), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
