# Generated by Django 5.2 on 2026-02-19 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_article_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 19, 17, 9, 26, 24140), editable=False, verbose_name='تاریخ ثبت'),
        ),
    ]
